function [quantized] = mydequantizer(index,recostruction )
%index is the index array generated by myquantizer
%reconstruction value is the ri
    for i = 1:length(index)
        quantized(i) = recostruction(index(i)+1);
    end
end

